=== lunajos/restaurant/data/schemas/Clients_Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <xsd:element name="client_information">
     <xsd:complexType>
       <xsd:sequence>
         <xsd:element name="client" type="clientType" minOccurs="0"
           maxOccurs="unbounded"/>
       </xsd:sequence>
     </xsd:complexType>
   </xsd:element>

   <xsd:complexType name="clientType">
     <xsd:sequence>
       <xsd:element name="client_number" type="xsd:integer"/>
       <xsd:element name="client_name" type="clientnameType"/>
       <xsd:element name="client_telephone_number" type="xsd:string"/>
       <xsd:element name="client_fax_number" type="xsd:string"/>
       <xsd:element name="client_address" type="clientaddressType"/>
       <xsd:element name="client_status" type="xsd:string"/>
      </xsd:sequence>
   </xsd:complexType>
   
    <xsd:complexType name="clientnameType">
     <xsd:sequence>
       <xsd:element name="client_name_family" type="xsd:string"/>
       <xsd:element name="client_name_given" type="xsd:string"/>
      </xsd:sequence>
   </xsd:complexType>
   
   <xsd:complexType name="clientaddressType">
     <xsd:sequence>
       <xsd:element name="client_address_street" type="xsd:string"/>
       <xsd:element name="client_address_city" type="xsd:string"/>
       <xsd:element name="client_address_state" type="xsd:string"/>
       <xsd:element name="client_address_postal_code" type="xsd:string"/>
      </xsd:sequence>
   </xsd:complexType>


 </xsd:schema>

=== lunajos/restaurant/src/data/Clients_PhaseA.xml
<?xml version="1.0" encoding="UTF-8"?>
<client_information xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schemas/Clients_Schema.xsd">
    <client>
        <client_number> 090012 </client_number>
        <client_name>
            <client_name_family> de Quillettes </client_name_family>
            <client_name_given> Frouke </client_name_given>
        </client_name>
        <client_telephone_number> +1 570 675 9277 </client_telephone_number>
        <client_fax_number> +1 570 675 7712 </client_fax_number>
        <client_address>
            <client_address_street> Old Route 115 </client_address_street>
            <client_address_city> Lehman </client_address_city>
            <client_address_state> PA </client_address_state>
            <client_address_postal_code> 18627 </client_address_postal_code>
        </client_address>
        <client_status> first-time </client_status>
    </client>

    <client>
        <client_number> 090013 </client_number>
        <client_name>
            <client_name_family> Luna </client_name_family>
            <client_name_given> Jose </client_name_given>
        </client_name>
        <client_telephone_number> +1 570 235 7070 </client_telephone_number>
        <client_fax_number> +1 570 235 8118 </client_fax_number>
        <client_address>
            <client_address_street> 113 Hilldale Avenue </client_address_street>
            <client_address_city> Plains </client_address_city>
            <client_address_state> PA </client_address_state>
            <client_address_postal_code> 18705 </client_address_postal_code>
        </client_address>
        <client_status> inactive </client_status>
    </client>

    <client>
        <client_number> 090014 </client_number>
        <client_name>
            <client_name_family> Snyder </client_name_family>
            <client_name_given> John </client_name_given>
        </client_name>
        <client_telephone_number> +1 570 823 7894</client_telephone_number>
        <client_fax_number> +1 570 823 8672 </client_fax_number>
        <client_address>
            <client_address_street> 25 Denise Court </client_address_street>
            <client_address_city> Wilkes Barre </client_address_city>
            <client_address_state> PA </client_address_state>
            <client_address_postal_code> 18702 </client_address_postal_code>
        </client_address>
        <client_status> repeat </client_status>
    </client>

    <client>
        <client_number> 090015 </client_number>
        <client_name>
            <client_name_family> Johnson </client_name_family>
            <client_name_given> Thomas </client_name_given>
        </client_name>
        <client_telephone_number> +1 570 894 7676</client_telephone_number>
        <client_fax_number> +1 570 894 7678 </client_fax_number>
        <client_address>
            <client_address_street> 29 Walnut Street</client_address_street>
            <client_address_city> Wilkes Barre </client_address_city>
            <client_address_state> PA </client_address_state>
            <client_address_postal_code> 18702 </client_address_postal_code>
        </client_address>
        <client_status> repeat </client_status>
    </client>
</client_information>
